#include <iostream>
#include <fstream>
using namespace std;
int main(int argc, char const *argv[])
{
    printf("b c g h | b->c | ~c or ~g | g or h | h->~c\n");
    bool b = true;
    bool c = true;
    bool g = true;
    bool h = true;
    printf("T T T T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
     b = true;
     c = true;
     g = true;
     h = false;
    printf("T T T F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
     b = true;
     c = true;
     g = false;
     h = true;
    printf("T T F T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
     b = true;
     c = true;
     g = false;
     h = false;
    printf("T T F F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = true;
     c = false;
     g = true;
     h = true;
    printf("T F T T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = true;
     c = false;
     g = true;
     h = false;
    printf("T F T F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = true;
     c = false;
     g = false;
     h = true;
    printf("T F F T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = true;
     c = false;
     g = false;
     h = false;
    printf("T F F F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = true;
     g = true;
     h = true;
    printf("F T T T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = true;
     g = true;
     h = false;
    printf("F T T F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = true;
     g = false;
     h = true;
    printf("F T F T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = true;
     g = false;
     h = false;
    printf("F T F F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = false;
     g = true;
     h = true;
    printf("F F T T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = false;
     g = true;
     h = false;
    printf("F F T F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = false;
     g = false;
     h = true;
    printf("F F F T |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
         b = false;
     c = false;
     g = false;
     h = false;
    printf("F F F F |  %d   |    %d     |   %d    |  %d  \n",!b||c,!c||!g,g||h,!h||!c);
}
